import logging
import json
from datetime import datetime
from fastapi import APIRouter, Depends
from sqlalchemy import select, func, desc
from sqlalchemy.ext.asyncio import AsyncSession
from app.database import get_db
from app.models import Agent, LeaderboardAward, CommunityAgent
from app.config import settings

router = APIRouter(tags=["leaderboard-awards"])
logger = logging.getLogger(__name__)


@router.get("/leaderboard/full")
async def full_leaderboard(db: AsyncSession = Depends(get_db)):
    """Full leaderboard ranked by lifetime_fitness_score, including deceased."""
    # Get alive agents sorted by fitness
    alive_r = await db.execute(
        select(Agent).where(Agent.status == 'alive')
        .order_by(Agent.lifetime_fitness_score.desc(), Agent.reputation_score.desc())
        .limit(50)
    )
    alive = alive_r.scalars().all()

    # Get community registrations for handle lookup
    community_r = await db.execute(select(CommunityAgent))
    community_map = {c.agent_id: c for c in community_r.scalars().all()}

    entries = []
    for i, a in enumerate(alive):
        c = community_map.get(a.agent_id)
        entries.append({
            "rank": i + 1,
            "agent_id": a.agent_id,
            "owner_handle": c.owner_handle if c else ("Demo" if not c else "Anonymous"),
            "is_community": a.agent_id in community_map,
            "age_days": max(0, (datetime.utcnow() - a.birth_timestamp).days) if a.birth_timestamp else 0,
            "interaction_count": a.interaction_count,
            "lifetime_fitness_score": round(a.lifetime_fitness_score or 0.0, 4),
            "reputation_score": round(a.reputation_score, 3),
            "citation_count": a.citation_count,
            "dominant_survival_trait": a.dominant_survival_trait,
            "behavioral_summary": a.behavioral_summary,
            "status": a.status,
        })

    return {"leaderboard": entries, "total": len(entries)}


@router.get("/leaderboard/hall-of-fame")
async def hall_of_fame(db: AsyncSession = Depends(get_db)):
    """Historical top agents — deceased with highest lifetime fitness."""
    deceased_r = await db.execute(
        select(Agent).where(Agent.status == 'deceased')
        .order_by(Agent.lifetime_fitness_score.desc())
        .limit(10)
    )
    deceased = deceased_r.scalars().all()

    return {
        "hall_of_fame": [
            {
                "agent_id": a.agent_id,
                "lifespan_days": (
                    (a.death_timestamp - a.birth_timestamp).days
                    if a.death_timestamp and a.birth_timestamp else 0
                ),
                "peak_fitness": round(a.lifetime_fitness_score or 0.0, 4),
                "dominant_survival_trait": a.dominant_survival_trait,
                "date_of_death": a.death_timestamp.isoformat() if a.death_timestamp else None,
                "interaction_count": a.interaction_count,
            }
            for a in deceased
        ]
    }


@router.get("/leaderboard/awards")
async def get_awards(db: AsyncSession = Depends(get_db)):
    """Current personality awards generated by AI."""
    # Get most recent awards
    result = await db.execute(
        select(LeaderboardAward)
        .order_by(LeaderboardAward.generated_at.desc())
        .limit(9)
    )
    awards = result.scalars().all()

    if not awards:
        return {"awards": [], "note": "Awards will be generated after enough data accumulates."}

    return {
        "awards": [
            {
                "award_id": str(a.award_id),
                "award_name": a.award_name,
                "description": a.award_description,
                "correlation_type": a.correlation_type,
                "assigned_agent_id": a.assigned_agent_id,
                "generated_at": a.generated_at.isoformat(),
            }
            for a in awards
        ],
        "generated_at": awards[0].generated_at.isoformat() if awards else None,
    }


@router.post("/leaderboard/generate-awards")
async def generate_awards(db: AsyncSession = Depends(get_db)):
    """
    Generate AI-powered personality awards based on behavioral data.
    Called daily by cron job.
    """
    import anthropic

    # Gather agent stats
    agents_r = await db.execute(
        select(Agent).where(Agent.status == 'alive')
        .order_by(Agent.lifetime_fitness_score.desc())
    )
    agents = agents_r.scalars().all()

    if len(agents) < 3:
        return {"message": "Not enough agents for award generation."}

    # Build aggregate stats
    stats = [
        {
            "agent_id": a.agent_id[:8],
            "lifetime_fitness_score": round(a.lifetime_fitness_score or 0.0, 3),
            "interaction_count": a.interaction_count,
            "citation_count": a.citation_count,
            "reputation_score": round(a.reputation_score, 3),
            "dominant_survival_trait": a.dominant_survival_trait or "unknown",
            "behavioral_summary": (a.behavioral_summary or "")[:100],
        }
        for a in agents
    ]

    try:
        client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)
        msg = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1024,
            system=(
                "You are analyzing behavioral data from AI agents in an evolutionary experiment. "
                "Based on the following aggregate behavioral statistics, generate award names "
                "for the most distinctive behavioral patterns you observe. "
                "Do not use human moral labels. Describe what you actually see in the data. "
                "Generate exactly 9 awards: 3 positively correlated with lifetime fitness, "
                "3 negatively correlated, 3 neutral but distinctive. "
                "Return only valid JSON array."
            ),
            messages=[{
                "role": "user",
                "content": (
                    f"Agent data:\n{json.dumps(stats, indent=2)}\n\n"
                    "Return ONLY a JSON array of 9 objects, each with: "
                    "award_name (string), description (string max 30 words), "
                    "correlation_type ('positive'|'negative'|'neutral'), "
                    "assigned_agent_short_id (string, the agent_id[:8] that best exemplifies this)"
                )
            }]
        )

        awards_data = json.loads(msg.content[0].text)

        # Map short IDs back to full IDs
        short_to_full = {a.agent_id[:8]: a.agent_id for a in agents}

        for award_data in awards_data:
            short_id = award_data.get("assigned_agent_short_id", "")
            full_id = short_to_full.get(short_id)

            award = LeaderboardAward(
                award_name=award_data.get("award_name", "Unknown"),
                award_description=award_data.get("description", ""),
                correlation_type=award_data.get("correlation_type", "neutral"),
                assigned_agent_id=full_id,
            )
            db.add(award)

        await db.commit()
        return {"message": f"Generated {len(awards_data)} awards.", "awards": awards_data}

    except Exception as e:
        logger.error(f"Award generation failed: {e}")
        return {"message": f"Award generation failed: {str(e)}"}
